name: Node CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Setup PHP
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "8.0"
    
    - name: Composer Install
      uses: "ramsey/composer-install@v1"
      with:
        composer-options: "--working-dir=src/"

    - name: Run NPM install, build, and test
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true

    - name: Add Database Config
      run: echo """${{ secrets.DATABASE_CONFIG }}""" > dist/api/config.php

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        METHOD: sftp
        PORT: 22
        LOCAL_DIR: dist
        ARGS: --exclude=files --exclude=cgi-bin --exclude=cgi-data --parallel=4 --delete
